BEGIN;

ALTER TABLE uat_olap.dim_country
ADD COLUMN IF NOT EXISTS country_code VARCHAR(2);

ALTER TABLE uat_olap.dim_country
ADD COLUMN IF NOT EXISTS country_name VARCHAR(100);

UPDATE uat_olap.dim_country
SET country_code = name
WHERE country_code IS NULL;

COMMIT;

UPDATE uat_olap.dim_country AS c
SET country_name = m.country_name
FROM (
    VALUES
        ('AE', 'United Arab Emirates'),
        ('AF', 'Afghanistan'),
        ('AL', 'Albania'),
        ('AO', 'Angola'),
        ('AR', 'Argentina'),
        ('AT', 'Austria'),
        ('AU', 'Australia'),
        ('BD', 'Bangladesh'),
        ('BE', 'Belgium'),
        ('BF', 'Burkina Faso'),
        ('BG', 'Bulgaria'),
        ('BR', 'Brazil'),
        ('BS', 'Bahamas'),
        ('BT', 'Bhutan'),
        ('BY', 'Belarus'),
        ('CA', 'Canada'),
        ('CD', 'Democratic Republic of the Congo'),
        ('CH', 'Switzerland'),
        ('CL', 'Chile'),
        ('CM', 'Cameroon'),
        ('CN', 'China'),
        ('CO', 'Colombia'),
        ('CU', 'Cuba'),
        ('CY', 'Cyprus'),
        ('CZ', 'Czechia'),
        ('DE', 'Germany'),
        ('DK', 'Denmark'),
        ('DZ', 'Algeria'),
        ('EG', 'Egypt'),
        ('ES', 'Spain'),
        ('FI', 'Finland'),
        ('FO', 'Faroe Islands'),
        ('FR', 'France'),
        ('GB', 'United Kingdom'),
        ('GE', 'Georgia'),
        ('GH', 'Ghana'),
        ('GL', 'Greenland'),
        ('GR', 'Greece'),
        ('GT', 'Guatemala'),
        ('HK', 'Hong Kong'),
        ('HR', 'Croatia'),
        ('HU', 'Hungary'),
        ('ID', 'Indonesia'),
        ('IE', 'Ireland'),
        ('IL', 'Israel'),
        ('IN', 'India'),
        ('IO', 'British Indian Ocean Territory'),
        ('IQ', 'Iraq'),
        ('IR', 'Iran'),
        ('IS', 'Iceland'),
        ('IT', 'Italy'),
        ('JO', 'Jordan'),
        ('JP', 'Japan'),
        ('KE', 'Kenya'),
        ('KG', 'Kyrgyzstan'),
        ('KH', 'Cambodia'),
        ('KN', 'Saint Kitts and Nevis'),
        ('KR', 'South Korea'),
        ('KW', 'Kuwait'),
        ('LB', 'Lebanon'),
        ('LK', 'Sri Lanka'),
        ('LT', 'Lithuania'),
        ('LU', 'Luxembourg'),
        ('MA', 'Morocco'),
        ('MC', 'Monaco'),
        ('MT', 'Malta'),
        ('MU', 'Mauritius'),
        ('MW', 'Malawi'),
        ('MX', 'Mexico'),
        ('MY', 'Malaysia'),
        ('NA', 'Namibia'),
        ('NG', 'Nigeria'),
        ('NL', 'Netherlands'),
        ('NO', 'Norway'),
        ('NP', 'Nepal'),
        ('NZ', 'New Zealand'),
        ('PE', 'Peru'),
        ('PH', 'Philippines'),
        ('PK', 'Pakistan'),
        ('PL', 'Poland'),
        ('PR', 'Puerto Rico'),
        ('PS', 'Palestine'),
        ('PT', 'Portugal'),
        ('PY', 'Paraguay'),
        ('QA', 'Qatar'),
        ('RO', 'Romania'),
        ('RS', 'Serbia'),
        ('RU', 'Russia'),
        ('SA', 'Saudi Arabia'),
        ('SE', 'Sweden'),
        ('SG', 'Singapore'),
        ('SN', 'Senegal'),
        ('SU', 'Soviet Union'),
        ('SY', 'Syria'),
        ('TH', 'Thailand'),
        ('TN', 'Tunisia'),
        ('TR', 'Türkiye'),
        ('TW', 'Taiwan'),
        ('TZ', 'Tanzania'),
        ('UA', 'Ukraine'),
        ('US', 'United States'),
        ('UY', 'Uruguay'),
        ('VA', 'Vatican City'),
        ('VE', 'Venezuela'),
        ('VN', 'Vietnam'),
        ('XX', 'Unknown / Unspecified'),
        ('ZA', 'South Africa'),
        ('ZW', 'Zimbabwe')
) AS m(country_code, country_name)
WHERE c.country_code = m.country_code;