-- ============================================================================
-- OLAP / analytics schema
-- Defines the dimensional model consumed by Power BI.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS analytics;


-- Title dimension.
CREATE TABLE IF NOT EXISTS analytics.dim_title (
    title_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_id TEXT NOT NULL UNIQUE,
    title_name TEXT NOT NULL,
    type TEXT NOT NULL,
    release_year INTEGER,
    age_certification VARCHAR(20),
    runtime INTEGER,
    seasons INTEGER,
    imdb_id TEXT
);


-- Person dimension.
CREATE TABLE IF NOT EXISTS analytics.dim_person (
    person_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INTEGER NOT NULL UNIQUE,
    name TEXT NOT NULL
);


-- Genre dimension.
CREATE TABLE IF NOT EXISTS analytics.dim_genre (
    genre_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_id INTEGER NOT NULL UNIQUE,
    name TEXT NOT NULL UNIQUE
);


-- Country dimension.
CREATE TABLE IF NOT EXISTS analytics.dim_country (
    country_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_id INTEGER NOT NULL UNIQUE,
    name TEXT NOT NULL UNIQUE
);


-- Bridge between title and genre dimensions.
CREATE TABLE IF NOT EXISTS analytics.bridge_title_genre (
    title_sk BIGINT NOT NULL
        REFERENCES analytics.dim_title(title_sk),

    genre_sk BIGINT NOT NULL
        REFERENCES analytics.dim_genre(genre_sk),

    PRIMARY KEY (title_sk, genre_sk)
);


-- Bridge between title and country dimensions.
CREATE TABLE IF NOT EXISTS analytics.bridge_title_country (
    title_sk BIGINT NOT NULL
        REFERENCES analytics.dim_title(title_sk),

    country_sk BIGINT NOT NULL
        REFERENCES analytics.dim_country(country_sk),

    PRIMARY KEY (title_sk, country_sk)
);


-- Credit fact table.
CREATE TABLE IF NOT EXISTS analytics.fact_credits (
    credit_sk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    title_sk BIGINT NOT NULL
        REFERENCES analytics.dim_title(title_sk),

    person_sk BIGINT NOT NULL
        REFERENCES analytics.dim_person(person_sk),

    role TEXT NOT NULL,
    character TEXT
);


-- Title metrics fact table.
CREATE TABLE IF NOT EXISTS analytics.fact_title_metrics (
    title_sk BIGINT PRIMARY KEY
        REFERENCES analytics.dim_title(title_sk),

    imdb_score NUMERIC,
    imdb_votes BIGINT,
    tmdb_popularity NUMERIC,
    tmdb_score NUMERIC
);


