-- ============================================================================
-- NETFLIX DATA ENGINEERING
-- OLTP / 3NF SCHEMA
-- ============================================================================
-- This layer contains the normalised relational model used between
-- raw staging and the final analytics/star-schema layer.

-- ============================================================================
-- TABLE 1: genre
-- ============================================================================

CREATE TABLE IF NOT EXISTS genre (
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);


-- ============================================================================
-- TABLE 2: country
-- ============================================================================
CREATE TABLE IF NOT EXISTS country (
    country_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);


-- ============================================================================
-- TABLE 3: title
-- ============================================================================
CREATE TABLE IF NOT EXISTS title (
    title_id TEXT PRIMARY KEY,
    title_name TEXT NOT NULL,
    type TEXT NOT NULL
        CHECK (type IN ('MOVIE', 'SHOW')),
    description TEXT,
    age_certification VARCHAR(20),
    runtime INTEGER,
    seasons INTEGER,
    imdb_id TEXT
);


-- ============================================================================
-- TABLE 4: person
-- ============================================================================
CREATE TABLE IF NOT EXISTS person (
    person_id INTEGER PRIMARY KEY,
        name TEXT NOT NULL
);


-- ============================================================================
-- TABLE 5: credit
-- ============================================================================
CREATE TABLE IF NOT EXISTS credit (
    credit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_id TEXT NOT NULL
        REFERENCES title(title_id),
    person_id INTEGER NOT NULL
        REFERENCES person(person_id),
    role TEXT NOT NULL
        CHECK (role IN ('ACTOR', 'DIRECTOR')),
    character TEXT
);


-- ============================================================================
-- TABLE 6: title_genre
-- ============================================================================

CREATE TABLE IF NOT EXISTS title_genre (
    title_id TEXT NOT NULL
        REFERENCES title(title_id),
    genre_id INTEGER NOT NULL
        REFERENCES genre(genre_id),
    PRIMARY KEY (title_id, genre_id)
);


-- ============================================================================
-- TABLE 7: title_country
-- ============================================================================
CREATE TABLE IF NOT EXISTS title_country (
    title_id TEXT NOT NULL
        REFERENCES title(title_id),
    country_id INTEGER NOT NULL
        REFERENCES country(country_id),
    PRIMARY KEY (title_id, country_id)
);


-- ============================================================================
-- INDEXES
-- ============================================================================
-- Foreign-key indexes are useful because later transformations and
-- analytics queries will repeatedly join these tables.
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_credit_title_id
ON credit(title_id);

CREATE INDEX IF NOT EXISTS idx_credit_person_id
ON credit(person_id);

CREATE INDEX IF NOT EXISTS idx_title_genre_title_id
ON title_genre(title_id);

CREATE INDEX IF NOT EXISTS idx_title_genre_genre_id
ON title_genre(genre_id);

CREATE INDEX IF NOT EXISTS idx_title_country_title_id
ON title_country(title_id);

CREATE INDEX IF NOT EXISTS idx_title_country_country_id
ON title_country(country_id);