-- ============================================================================
-- NETFLIX DATA ENGINEERING
-- OLTP / 3NF SCHEMA
-- ============================================================================
-- This layer contains the normalised relational model used between
-- raw staging and the final analytics/star-schema layer.
--
-- The raw staging layer is intentionally flexible.
-- This OLTP layer is stricter because data has already been validated
-- and transformed before reaching these tables.
-- ============================================================================


-- ============================================================================
-- TABLE 1: genre
-- ============================================================================
-- Stores one unique row for every genre found in the Netflix source data.
-- Examples: Drama, Comedy, Action, Thriller.
-- ============================================================================

CREATE TABLE IF NOT EXISTS genre (

    -- Surrogate key generated automatically by PostgreSQL.
    -- We do not manually calculate genre IDs because future incremental
    -- batches may introduce new genres.
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Human-readable genre name.
    -- UNIQUE prevents the same genre from being inserted more than once.
    name TEXT NOT NULL UNIQUE

);


-- ============================================================================
-- TABLE 2: country
-- ============================================================================
-- Stores one unique row for every production country.
-- Examples: United States, United Kingdom, Nigeria.
-- ============================================================================

CREATE TABLE IF NOT EXISTS country (

    -- Surrogate country identifier managed by PostgreSQL.
    country_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Country name from the cleaned source data.
    -- UNIQUE prevents duplicate country records.
    name TEXT NOT NULL UNIQUE

);


-- ============================================================================
-- TABLE 3: title
-- ============================================================================
-- Stores the main Netflix title record.
-- A title may represent either a movie or a TV show.
-- ============================================================================

CREATE TABLE IF NOT EXISTS title (

    -- Natural identifier supplied by the Netflix source.
    -- Example: tm84618.
    title_id TEXT PRIMARY KEY,

    -- Human-readable movie/show title.
    title_name TEXT NOT NULL,

    -- Identifies whether the title is a MOVIE or SHOW.
    -- The CHECK constraint prevents unexpected values.
    type TEXT NOT NULL
        CHECK (type IN ('MOVIE', 'SHOW')),

    -- Long-form title description.
    description TEXT,

    -- Netflix age/certification classification.
    -- Example values may include PG, TV-MA, R, etc.
    age_certification VARCHAR(20),

    -- Runtime in minutes.
    -- At this stage it is stored as an integer because raw text
    -- values should already have been validated during transformation.
    runtime INTEGER,

    -- Number of seasons for TV shows.
    -- Movie records will normally contain NULL.
    seasons INTEGER,

    -- External IMDb identifier.
    imdb_id TEXT

);


-- ============================================================================
-- TABLE 4: person
-- ============================================================================
-- Stores unique people appearing in the credits source.
-- These may include actors, directors, and other credited people.
-- ============================================================================

CREATE TABLE IF NOT EXISTS person (

    -- Person identifier supplied by the credits source.
    person_id INTEGER PRIMARY KEY,

    -- Full name of the credited person.
    name TEXT NOT NULL

);


-- ============================================================================
-- TABLE 5: credit
-- ============================================================================
-- Represents the relationship between a Netflix title and a person.
--
-- Example:
-- Breaking Bad
--      ↓
-- Bryan Cranston
--      ↓
-- ACTOR
-- ============================================================================

CREATE TABLE IF NOT EXISTS credit (

    -- Surrogate identifier for the individual credit relationship.
    -- PostgreSQL generates this automatically.
    credit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Netflix title associated with this credit.
    -- The foreign key ensures the referenced title already exists.
    title_id TEXT NOT NULL
        REFERENCES title(title_id),

    -- Person associated with the credit.
    -- The foreign key ensures the person exists in the person table.
    person_id INTEGER NOT NULL
        REFERENCES person(person_id),

    -- Role performed by this person for the title.
    -- Restrict the accepted values to the roles currently supported
    -- by the dataset.
    role TEXT NOT NULL
        CHECK (role IN ('ACTOR', 'DIRECTOR')),

    -- Character played by an actor.
    -- Directors and some other credits may contain NULL.
    character TEXT

);


-- ============================================================================
-- TABLE 6: title_genre
-- ============================================================================
-- Bridge table connecting titles to genres.
--
-- A title can have many genres.
-- A genre can belong to many titles.
--
-- Therefore this is a many-to-many relationship.
-- ============================================================================

CREATE TABLE IF NOT EXISTS title_genre (

    -- Netflix title participating in the relationship.
    title_id TEXT NOT NULL
        REFERENCES title(title_id),

    -- Genre associated with the title.
    genre_id INTEGER NOT NULL
        REFERENCES genre(genre_id),

    -- Composite primary key prevents the same title/genre
    -- relationship from being inserted more than once.
    PRIMARY KEY (title_id, genre_id)

);


-- ============================================================================
-- TABLE 7: title_country
-- ============================================================================
-- Bridge table connecting titles to production countries.
--
-- A title may be produced in multiple countries.
-- A country may be associated with many titles.
-- ============================================================================

CREATE TABLE IF NOT EXISTS title_country (

    -- Netflix title participating in the relationship.
    title_id TEXT NOT NULL
        REFERENCES title(title_id),

    -- Production country associated with the title.
    country_id INTEGER NOT NULL
        REFERENCES country(country_id),

    -- Composite primary key prevents duplicate title/country relationships.
    PRIMARY KEY (title_id, country_id)

);


-- ============================================================================
-- INDEXES
-- ============================================================================
-- Foreign-key indexes are useful because later transformations and
-- analytics queries will repeatedly join these tables.
-- ============================================================================


-- Improve searches and joins using title_id inside the credit table.
CREATE INDEX IF NOT EXISTS idx_credit_title_id
ON credit(title_id);


-- Improve searches and joins using person_id inside the credit table.
CREATE INDEX IF NOT EXISTS idx_credit_person_id
ON credit(person_id);


-- Improve title-based lookups in the title_genre bridge.
CREATE INDEX IF NOT EXISTS idx_title_genre_title_id
ON title_genre(title_id);


-- Improve genre-based lookups in the title_genre bridge.
CREATE INDEX IF NOT EXISTS idx_title_genre_genre_id
ON title_genre(genre_id);


-- Improve title-based lookups in the title_country bridge.
CREATE INDEX IF NOT EXISTS idx_title_country_title_id
ON title_country(title_id);


-- Improve country-based lookups in the title_country bridge.
CREATE INDEX IF NOT EXISTS idx_title_country_country_id
ON title_country(country_id);